version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: gogames_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gogames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gogames_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "gabrielh2007.scs@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
